title: Teste
author: eumesmo
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  venha testar
  este site fantastico

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
